import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <div className="flex justify-between p-10 font-bold text-xl">
          <button className="cursor-pointer">Menu</button>
          <button className="cursor-pointer">
            <Link href={"/"}>Atalanta Kelly</Link>
          </button>
          <button className="cursor-pointer">Cart</button>
        </div>
        {children}
      </body>
    </html>
  );
}
